version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: monitoruser
      POSTGRES_PASSWORD: monitorpass
      POSTGRES_DB: monitorweb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitorweb
      SPRING_DATASOURCE_USERNAME: monitoruser
      SPRING_DATASOURCE_PASSWORD: monitorpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    restart: on-failure
    command: ["sh", "-c", "./wait-for-postgres.sh postgres 5432 -- java -jar app.jar"]

volumes:
  pgdata:
